/**
 * Single source of truth for the site's page registry.
 *
 * Drives the build-time generators for /llms.txt and /llms-full.txt
 * (src/pages/llms.txt.ts, llms-full.txt.ts).
 *
 * NOTE on the sitemap: this site's sitemap is produced by the official
 * `@astrojs/sitemap` integration (→ /sitemap-index.xml), which auto-discovers
 * all routes. The `sitemap` flag below is therefore informational / reserved
 * for a future registry-driven sitemap; it does not currently emit anything.
 * The `llms` flag is the one that matters here.
 *
 * Add a page here ONCE (with its real title + meta description) and the llms
 * files stay in sync. Dynamic content (blog posts) is pulled from Sanity at
 * build time by the generators, so it needs no static entry.
 */

export const SITE_URL = "https://www.basiq.work";

/** Every "Book a call" CTA on the site points here. */
export const BOOKING_URL = "https://booking.akiflow.com/basiq-consulting";

export type Section = "Core" | "What we do" | "Products" | "Masterclass" | "Resources";

export interface SitePage {
  /** Path relative to the site root, no trailing slash (use "/" for home). */
  path: string;
  /** Short label used as the link text in llms.txt. */
  title: string;
  /** One-line annotation used in llms.txt. Pulled from each page's real meta description. */
  description: string;
  section: Section;
  /** Reserved — sitemap is currently generated by @astrojs/sitemap. */
  sitemap: boolean;
  /** Include in llms.txt / llms-full.txt. */
  llms: boolean;
}

export const sitePages: SitePage[] = [
  // ── Core ──────────────────────────────────────────────────────────────
  {
    path: "/",
    title: "Basiq",
    description:
      "An AI execution partner for companies that need working systems, not slide decks. Basiq embeds with your team, builds production systems, then hands off ownership.",
    section: "Core",
    sitemap: true,
    llms: true,
  },

  // ── What we do ────────────────────────────────────────────────────────
  {
    path: "/ai-strategy",
    title: "AI Strategy",
    description:
      "Where to start, what to build, how to sequence it. Map your highest-leverage entry points and prove them with working prototypes — from diagnostic to fully AI-enabled.",
    section: "What we do",
    sitemap: true,
    llms: true,
  },
  {
    path: "/engineering",
    title: "Engineering",
    description:
      "Go from AI-curious to AI-native. Build an engineering org that runs AI end-to-end, with production tools your team owns.",
    section: "What we do",
    sitemap: true,
    llms: true,
  },
  {
    path: "/go-to-market",
    title: "Go-to-Market",
    description:
      "AI-powered sales, CS, and marketing. A GTM motion that runs on signal, not instinct — automated prospecting, signal-based forecasting, and call intelligence.",
    section: "What we do",
    sitemap: true,
    llms: true,
  },
  {
    path: "/operations",
    title: "Operations",
    description:
      "AI as a default for every employee, not just the tech team — writing, research, and intelligence across the org.",
    section: "What we do",
    sitemap: true,
    llms: true,
  },
  {
    path: "/business-applications",
    title: "Business Applications",
    description:
      "Turn your process experts into builders. Internal apps built by the people who need them, with engineers supervising.",
    section: "What we do",
    sitemap: true,
    llms: true,
  },

  // ── Products ──────────────────────────────────────────────────────────
  // Topiq (gettopiq.ai) and Musal (musal.ai) live on their own domains and have
  // no page here — they're covered by the /products hub. Copy lives in src/lib/products.ts.
  {
    path: "/products",
    title: "Products",
    description:
      "The Basiq product suite — Topiq, Fabriq, Musal, Qindle, and LaneScout. AI systems for sales, customer success, prompt operations, prospecting, and freight.",
    section: "Products",
    sitemap: true,
    llms: true,
  },
  {
    path: "/products/fabriq",
    title: "Fabriq",
    description:
      "AI-powered customer intelligence for CS leaders managing net retention at scale. Stakeholder sentiment, expansion signal, and evidence-based renewal forecasts.",
    section: "Products",
    sitemap: true,
    llms: true,
  },
  {
    path: "/products/qindle",
    title: "Qindle",
    description:
      "The only prospecting CRM built for Account Executives to focus on account and prospect discovery and the human parts of pipe gen: cold calling and video.",
    section: "Products",
    sitemap: true,
    llms: true,
  },
  {
    path: "/products/lanescout",
    title: "LaneScout",
    description:
      "AI-powered negotiation coaching that turns your carrier desk into a margin engine. Built for US freight brokers. Coming soon from Basiq.",
    section: "Products",
    sitemap: true,
    llms: true,
  },

  // ── Masterclass ───────────────────────────────────────────────────────
  {
    path: "/masterclass/claude-code-101",
    title: "Claude Code 101",
    description:
      "A hands-on introduction for non-technical teams: get Claude Code installed, learn command-line basics, and start building real apps and automations in plain English.",
    section: "Masterclass",
    sitemap: true,
    llms: true,
  },
  {
    path: "/masterclass/claude-code-website",
    title: "Build a Website with Claude Code",
    description:
      "Step-by-step AI masterclass: build and deploy a professional website using Claude Code. No coding experience required.",
    section: "Masterclass",
    sitemap: true,
    llms: true,
  },

  // ── Resources ─────────────────────────────────────────────────────────
  {
    path: "/blog",
    title: "Blog",
    description: "Insights and updates from the Basiq team.",
    section: "Resources",
    sitemap: true,
    llms: true,
  },
];

/** Absolute URL for a registry path. */
export function absUrl(path: string): string {
  return path === "/" ? `${SITE_URL}/` : `${SITE_URL}${path}`;
}

export const SECTION_ORDER: Section[] = [
  "Core",
  "What we do",
  "Products",
  "Masterclass",
  "Resources",
];
