/**
 * Single source of truth for the site's page registry.
 *
 * Drives the build-time generators for /llms.txt and /llms-full.txt
 * (src/pages/llms.txt.ts, llms-full.txt.ts).
 *
 * NOTE on the sitemap: this site's sitemap is produced by the official
 * `@astrojs/sitemap` integration (→ /sitemap-index.xml), which auto-discovers
 * all routes. The `sitemap` flag below is therefore informational / reserved
 * for a future registry-driven sitemap; it does not currently emit anything.
 * The `llms` flag is the one that matters here.
 *
 * Add a page here ONCE (with its real title + meta description) and the llms
 * files stay in sync. Dynamic content (blog posts) is pulled from Sanity at
 * build time by the generators, so it needs no static entry.
 */

export const SITE_URL = "https://www.basiq.work";

/** Every "Book a call" CTA on the site points here. */
export const BOOKING_URL = "https://booking.akiflow.com/basiq-consulting";

export type Section = "Core" | "Solutions" | "Products" | "Masterclass" | "Resources";

export interface SitePage {
  /** Path relative to the site root, no trailing slash (use "/" for home). */
  path: string;
  /** Short label used as the link text in llms.txt. */
  title: string;
  /** One-line annotation used in llms.txt. Pulled from each page's real meta description. */
  description: string;
  section: Section;
  /** Reserved. The sitemap is currently generated by @astrojs/sitemap. */
  sitemap: boolean;
  /** Include in llms.txt / llms-full.txt. */
  llms: boolean;
}

export const sitePages: SitePage[] = [
  // ── Core ──────────────────────────────────────────────────────────────
  {
    path: "/",
    title: "Basiq",
    description:
      "A revenue execution platform that runs off meeting transcripts instead of CRM data entry. Sellers get every task needed to generate pipeline, close deals and grow customers, served in priority order.",
    section: "Core",
    sitemap: true,
    llms: true,
  },

  // ── Solutions ─────────────────────────────────────────────────────────
  // One page per audience in src/lib/personas.ts. The five "What we do" pages
  // that used to sit here were retired and now 301 to the homepage.
  {
    path: "/founders",
    title: "For Founders and CEOs",
    description:
      "Basiq is the revenue execution platform for founders and CEOs who need production systems, not a strategy deck. We embed, build in weeks, and hand off ownership.",
    section: "Solutions",
    sitemap: true,
    llms: true,
  },
  {
    path: "/revenue-leaders",
    title: "For CROs and VPs of Sales",
    description:
      "Basiq builds AI systems for revenue teams: automated prospecting, reply handling, call intelligence, and signal-based forecasting. Production systems your team owns.",
    section: "Solutions",
    sitemap: true,
    llms: true,
  },

  // ── Products ──────────────────────────────────────────────────────────
  // Topiq (gettopiq.ai) and Musal (musal.ai) live on their own domains and have
  // no page here; they're covered by the /products hub. Copy lives in src/lib/products.ts.
  {
    path: "/products",
    title: "Products",
    description:
      "The Basiq product suite: Topiq, Fabriq, Musal, and Qindle. AI systems for sales, customer success, prompt operations, and prospecting.",
    section: "Products",
    sitemap: true,
    llms: true,
  },
  {
    path: "/products/fabriq",
    title: "Fabriq",
    description:
      "AI-powered customer intelligence for CS leaders managing net retention at scale. Stakeholder sentiment, expansion signal, and evidence-based renewal forecasts.",
    section: "Products",
    sitemap: true,
    llms: true,
  },
  {
    path: "/products/qindle",
    title: "Qindle",
    description:
      "The only prospecting CRM built for Account Executives to focus on account and prospect discovery and the human parts of pipe gen: cold calling and video.",
    section: "Products",
    sitemap: true,
    llms: true,
  },

  // ── Masterclass ───────────────────────────────────────────────────────
  {
    path: "/masterclass/claude-code-101",
    title: "Claude Code 101",
    description:
      "A hands-on introduction for non-technical teams: get Claude Code installed, learn command-line basics, and start building real apps and automations in plain English.",
    section: "Masterclass",
    sitemap: true,
    llms: true,
  },
  {
    path: "/masterclass/claude-code-website",
    title: "Build a Website with Claude Code",
    description:
      "Step-by-step AI masterclass: build and deploy a professional website using Claude Code. No coding experience required.",
    section: "Masterclass",
    sitemap: true,
    llms: true,
  },

  // ── Resources ─────────────────────────────────────────────────────────
  {
    path: "/blog",
    title: "Blog",
    description: "Insights and updates from the Basiq team.",
    section: "Resources",
    sitemap: true,
    llms: true,
  },
  {
    // Canonicals to basiq.work. Episode detail pages live at /episode/[slug]
    // and come from Sanity, so they need no static entry here.
    path: "/podcast",
    title: "Selling AI Podcast",
    description:
      "The podcast for revenue teams selling and using AI. Conversations with founders, CROs, and AEs on selling AI products and using AI to sell smarter.",
    section: "Resources",
    sitemap: true,
    llms: true,
  },
  {
    path: "/best-ai-sales-assistant-software-2026",
    title: "8 Best AI Sales Assistant Tools for 2026",
    description:
      "Buyer's guide comparing 8 AI sales assistants across opportunity management, data enrichment, cold calling, CRM, and forecasting, with features, pricing, and use cases.",
    section: "Resources",
    sitemap: true,
    llms: true,
  },
];

/** Absolute URL for a registry path. */
export function absUrl(path: string): string {
  return path === "/" ? `${SITE_URL}/` : `${SITE_URL}${path}`;
}

export const SECTION_ORDER: Section[] = [
  "Core",
  "Solutions",
  "Products",
  "Masterclass",
  "Resources",
];
